---

# Instalacion de paquetes requeridos definidos en group-vars/packages.yaml
# https://docs.ansible.com/ansible/2.9/modules/package_module.html
- name: Instalamos paquetes definidos en group-vars/packages.yaml
  dnf:
    name: "{{ paquetes }}"
    state: present
