---

# Playbook realizar tareas comunes a todas las maquinas virtuales
- name: tareas comunes todos las maquinas virtuales
  hosts: all
  vars_files:
    - "group_vars/timezone.yaml"
  gather_facts: false
  roles:
    - timezone
  become: yes
