---

# Playbook realizar tareas comunes a todas las maquinas virtuales
- name: tareas comunes todos las maquinas virtuales
  hosts: all
  become: true
  vars_files:
    - "group-vars/timezone.yaml"
  gather_facts: false
  roles:
    - timezone
