---

# Playbook de instalacion de servidor nfs
# NFS no será necesario añadir un disco según se indica en la guia de apoyo
- name: Instalacion servidor nfs (sin añadir disco, no necesario segun guia de apoyo)
  hosts: all
  become: true
  vars_files:
    - "group-vars/paquetes-nfs.yaml"
    - "group-vars/ips.yaml"
    - "group-vars/firewall-nfs.yaml"
  gather_facts: false
  roles:
    - nfs
